"""Add GitHub integration models

Revision ID: 1c1b73eab012
Revises: 49c5cc829ef5
Create Date: 2026-05-31 12:41:46.787705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c1b73eab012'
down_revision: Union[str, None] = '49c5cc829ef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(), nullable=False),
    sa.Column('ref_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_activities_id'), 'github_activities', ['id'], unique=False)
    op.create_index(op.f('ix_github_activities_project_id'), 'github_activities', ['project_id'], unique=False)
    op.create_table('project_github_repos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('repo_full_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_github_repos_id'), 'project_github_repos', ['id'], unique=False)
    op.create_index(op.f('ix_project_github_repos_project_id'), 'project_github_repos', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_github_repos_project_id'), table_name='project_github_repos')
    op.drop_index(op.f('ix_project_github_repos_id'), table_name='project_github_repos')
    op.drop_table('project_github_repos')
    op.drop_index(op.f('ix_github_activities_project_id'), table_name='github_activities')
    op.drop_index(op.f('ix_github_activities_id'), table_name='github_activities')
    op.drop_table('github_activities')
    # ### end Alembic commands ###
