"""Add project_id to Note

Revision ID: 49c5cc829ef5
Revises: d756028b7692
Create Date: 2026-05-31 12:38:42.445214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49c5cc829ef5'
down_revision: Union[str, None] = 'd756028b7692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_notes_project_id'), 'notes', ['project_id'], unique=False)
    op.create_foreign_key(None, 'notes', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_index(op.f('ix_notes_project_id'), table_name='notes')
    op.drop_column('notes', 'project_id')
    # ### end Alembic commands ###
