"""github_integration

Revision ID: fa037dae68ca
Revises: 64ac032f4b2b
Create Date: 2026-05-27 13:06:08.793325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa037dae68ca'
down_revision: Union[str, None] = '64ac032f4b2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('commits', sa.Integer(), nullable=True),
    sa.Column('repositories', sa.Integer(), nullable=True),
    sa.Column('pull_requests', sa.Integer(), nullable=True),
    sa.Column('top_languages', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_github_stats_id'), 'github_stats', ['id'], unique=False)
    op.add_column('users', sa.Column('github_access_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('github_username', sa.String(), nullable=True))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'user'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'user'::character varying"))
    op.drop_column('users', 'github_username')
    op.drop_column('users', 'github_access_token')
    op.drop_index(op.f('ix_github_stats_id'), table_name='github_stats')
    op.drop_table('github_stats')
    # ### end Alembic commands ###
